version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-Backend
    container_name: backend
    restart: unless-stopped
    ports:
      - "9000:9000"
    volumes:
      - ./backend:/var/www/html
    depends_on:
      - mysql
    networks:
      - backend_network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-Frontend
    container_name: frontend
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - ./frontend:/app
 

  mysql:
    image: mysql:5.7
    container_name: db
    restart: unless-stopped
    platform: linux/x86_64
    ports:
      - "4000:3306"
    expose:
      - '4000'
    environment:
      MYSQL_ROOT_PASSWORD: kevi
      MYSQL_DATABASE: kevi
      MYSQL_USER: kevi
      MYSQL_PASSWORD: kevi
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend_network

networks:
  backend_network:

volumes:
  mysql_data:
    driver: local
