openapi: 3.0.0
info:
  version: 1.0.0
  title: Funny Reminders API
  description: API Docs for funny reminders associed with characters
  contact:
    email: contato@seudominio.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/DURVALJUNIOR117/FunnyRemindersAPI/1.0.0
  - url: http://localhost:8000
    description: Servidor local
paths:
  /reminder:
    post:
      tags:
        - Reminders
      summary: Create a new reminder
      description: Creates a new reminder with the provided content and character ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateReminderInput'
      responses:
        '200':
          description: Reminder created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  originalMessage:
                    type: string
                  processedMessage:
                    type: string
                  date:
                    type: string
                  createdAt:
                    type: string
                  characterId:
                    type: string
                  send:
                    type: boolean
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /reminders:
    get:
      tags:
        - Reminders
      summary: List reminders
      description: Lists reminders with optional filters for pagination and status
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            default: 1
          description: Page number for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          description: Number of reminders per page
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum:
              - send
              - notSend
            default: notSend
          description: Filter reminders by send status
      responses:
        '200':
          description: List of reminders
          content:
            application/json:
              schema:
                type: object
                properties:
                  reminders:
                    type: array
                    items:
                      $ref: '#/components/schemas/ListRemindersOutput'
                  total:
                    type: integer
                    description: Total number of reminders
                  perPage:
                    type: integer
                    description: Number of reminders per page
                  currentPage:
                    type: integer
                    description: Current page number
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /reminder/{id}:
    delete:
      tags:
        - Reminders
      summary: Delete a reminder
      description: Deletes a reminder by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the reminder to delete
      responses:
        '200':
          description: Reminder deleted successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '404':
          description: Reminder not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /reminder/{id}/send:
    put:
      tags:
        - Reminders
      summary: Send a reminder
      description: Sends a reminder by its ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: ID of the reminder to send
      responses:
        '200':
          description: Reminder sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    description: Success message
        '403':
          description: Forbidden
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    description: Error message
        '404':
          description: Reminder not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
  /characters:
    get:
      tags:
        - Characters
      summary: List characters
      description: Retrieves a list of characters with optional pagination
      parameters:
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
          description: The page number for pagination
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 20
          description: The number of items per page
      responses:
        '200':
          description: A list of characters
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListCharactersOutput'
        '422':
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string

components:
  schemas:
    CreateReminderInput:
      type: object
      required:
        - content
        - characterId
      properties:
        content:
          type: string
          description: The content of the reminder
        characterId:
          type: string
          description: The ID of the character associated with the reminder
    CreateReminderOutput:
      type: object
      properties:
        id:
          type: string
          description: ID of the reminder
        originalMessage:
          type: string
          description: The original message of the reminder
        processedMessage:
          type: string
          description: The processed message of the reminder
        date:
          type: string
          description: The date of the reminder
        createdAt:
          type: string
          description: The creation date of the reminder
        characterId:
          type: string
          description: The ID of the character associated with the reminder
        send:
          type: boolean
          description: Indicates whether the reminder should be sent
    ListRemindersOutput:
      type: object
      properties:
        id:
          type: string
          description: The ID of the reminder
        originalMessage:
          type: string
          description: The original message of the reminder
        processedMessage:
          type: string
          description: The processed message of the reminder
        date:
          type: string
          description: The date of the reminder
        createdAt:
          type: string
          description: The creation date of the reminder
      
        send:
          type: boolean
          description: Indicates whether the reminder should be sent
        character:
          type: object
          properties: 
            id:
              type: string
              description: The ID of the character associated with the reminder
            name:
              type: string
              description: The name of the character associated with the reminder
            humor:
              type: string
              description: The humor of the character associated with the reminder
            role:
              type: string
              description: The role of the character associated with the reminder
            ageVitality:
              type: string
              description: The age and vitality of the character associated with the reminder
            origin:
              type: string
              description: The origin of the character associated with the reminder
            speechMannerisms:
              type: string
              description: The speech mannerisms of the character associated with the reminder
            accent:
              type: string
              description: The accent of the character associated with the reminder
            archetype:
              type: string
              description: The archetype of the character associated with the reminder
            imagePath:
              type: string
              description: The image path of the character associated with the reminder
    ListCharactersOutput:
      type: object
      properties:
        characters:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              name:
                type: string
              humor:
                type: string
              role:
                type: string
              ageVitality:
                type: string
              origin:
                type: string
              speechMannerisms:
                type: string
              accent:
                type: string
              archetype:
                type: string
              imagePath:
                type: string
        total:
          type: integer
          description: Total number of characters
        perPage:
          type: integer
          description: Number of characters per page
        currentPage:
          type: integer
          description: Current page number